service: aws-serverless-nodejs-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: mikaeel

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: mikaeel-serverless-bucket
      localDir: UploadData

functions:
  getUser:
    handler: lambdas/getUser.handler
    events:
      - http:
          path: get-users/{ID}
          method: GET
          cors: true

resources:
  Resources:
    DemoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mikaeel-serverless-bucket
