service: aws-serverless-nodejs-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: mikaeel

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    DemoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mikaeel-serverless-bucket
